name: Deploy Python project to Azure Function App with Microsoft Graph Integration

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: 'EliteDynamicsFuncions'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Generate Microsoft Graph Token
      id: generate_token
      run: |
        curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
          -d "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -d "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
          -d "scope=https://graph.microsoft.com/.default" \
          -d "grant_type=client_credentials" \
          "https://login.microsoftonline.com/${{ secrets.AZURE_TENANT_ID }}/oauth2/v2.0/token" \
          -o token.json
        echo "GRAPH_ACCESS_TOKEN=$(jq -r .access_token token.json)" >> $GITHUB_ENV

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Test Microsoft Graph Integration
      run: |
        curl -X GET -H "Authorization: Bearer $GRAPH_ACCESS_TOKEN" \
          https://graph.microsoft.com/v1.0/me
