name: Deploy Python project to Azure Function App with Microsoft Graph Integration

on:
  push:
    branches:
      - main  # El workflow se ejecutará al hacer push a la rama principal.

env:
  AZURE_FUNCTIONAPP_NAME: 'EliteDynamicsFuncions'  # Nombre de tu Azure Function App.
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'              # Ruta del proyecto, raíz del repositorio.
  PYTHON_VERSION: '3.11'                           # Versión de Python que usas.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # Secreto configurado en GitHub.

    - name: Test Microsoft Graph Integration
      run: |
        python -c "
        import requests
        url = 'https://graph.microsoft.com/v1.0/me'
        headers = {'Authorization': f'Bearer {secrets.GRAPH_ACCESS_TOKEN}'}
        response = requests.get(url, headers=headers)
        print(response.json())
        "
